### PR TITLE
Build Action-like objects from WrittenMessages

### PR DESCRIPTION
**Pull request by jml**
Currently just a design doc for the rest of #181.

[Review on Reviewable](https://reviewable.io/reviews/clusterhq/eliot/188)

### CODE REVIEW

**Comment by itamarst** [comment]
Brain dump, so I have some context for reading this:


My personal top use case is extracting errors. And probably the way you want to do that is have a two-phase scan:

1. Scan on-disk (or Elasticsearch logs or whatever) for failed actions, tracebacks and errors forwarded from Twisted logs (this is Flocker-specific for now but we do want to move that code to Eliot).
2. Calculate the set of `task_id` values from messages found in step 1.
3. Scan on-disk logs for all messages with that `task_id`.

Probably for many issues the output of step 1 is sufficient. Others would need output of step 3. Conceivably some would need even more logs but that's going to be a lot less common.

Moreover:
1. It's impossible to know when an action is *really* done given cross-process actions.
2. Crashes etc. mean some actions will never have their final messages.
3. Memory restriction is a policy choice that has to be available, but needn't be enforced so long as API user can choose to do so.

**Comment by itamarst** [comment]
Bleh. Still not sure where this should go. Possibly because it doesn't actually match the interaction pattern for my use case above. Will return to this later.

**Comment by jml** [comment]
Errors is one of my two major cases. The other is gathering stats about durations of a particular type of action.

What I'll do is provide the basic building blocks for this, as well as convenience functions that use them in a way that's useful to me right here & now. That way, when we want to handle other, trickier cases we can (hopefully) just add code, rather than changing the base-level types.

**Comment by jml** [comment]
This has been dealt with in other parsing work.

**Pull request closed without merging**
