### PR TITLE
Native Journald support

### LINKED ISSUE #207: journald support
journald is increasingly common on Linux systems; in two years probably all of them. Eliot should have good support.

1. task_id and maybe message/action type should be journald fields, so you can query by them.
2. tracebacks and failed actions should be marked with error priority.

### PR DESCRIPTION
**Pull request by itamarst**
Fixes #207.

[Review on Reviewable](https://reviewable.io/reviews/clusterhq/eliot/210)

### CODE REVIEW

**Comment by tomprince** [comment]
It would be nice if there were some way to specify something like `SYSLOG_IDENTIFIER`. Right now the example has `SYSLOG_IDENTIFIER=python` and there doesn't appear to be any way to change it (or otherwise identify messages as belonging together in a way queryable from `journalctl`. Perhaps out-of-scope here, though.

I get a bunch of test failures running the tests locally.

Please resubmit after addressing the review comments.


---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

<sup>**[docs/source/journald.rst, line 11 \[r1\]](https://reviewable.io:443/reviews/clusterhq/eliot/210#-K-PNRZeB71ZxrhTuOc5)** ([raw file](https://github.com/clusterhq/eliot/blob/a2baabc46b3063ba9c3c3dc6564e1f9d2e331ce9/docs/source/journald.rst#L11)):</sup>
This makes me wonder if the distinction between `message_type` and `action_type` in eliot logs is valuable.


---

<sup>**[docs/source/journald.rst, line 24 \[r1\]](https://reviewable.io:443/reviews/clusterhq/eliot/210#-K-PX_EeQKNs-pU0AF-e)** ([raw file](https://github.com/clusterhq/eliot/blob/a2baabc46b3063ba9c3c3dc6564e1f9d2e331ce9/docs/source/journald.rst#L24)):</sup>
This all works and is slick.


---

<sup>**[eliot/journald.py, line 17 \[r1\]](https://reviewable.io:443/reviews/clusterhq/eliot/210#-K-PV9dMZuBV9HqtKQ_T)** ([raw file](https://github.com/clusterhq/eliot/blob/a2baabc46b3063ba9c3c3dc6564e1f9d2e331ce9/eliot/journald.py#L17)):</sup>
This doesn't work on Fedora 22 or Gentoo unstable.

systemd-209 made libsystemd-journald.so just a compatility library (see [here](https://github.com/systemd/systemd/blob/master/NEWS#L2774-L2796)) which isn't installed on newer distributions.

I guess maybe we want to try this and then fallback to `libsystemd`. Or the other way around would be better (if it `cffi` is smart enough to fail if `libsystemd` doesn't have the required symbols).


---

<sup>**[eliot/tests/test_journald.py, line 29 \[r1\]](https://reviewable.io:443/reviews/clusterhq/eliot/210#-K-P_asY00EhtzeZmMeE)** ([raw file](https://github.com/clusterhq/eliot/blob/a2baabc46b3063ba9c3c3dc6564e1f9d2e331ce9/eliot/tests/test_journald.py#L29)):</sup>
Maybe put an `-n1` here or something, so as not to generate tons of output. (`-n0` appears to exit with success even without a journals)


---

<sup>**[eliot/tests/test_journald.py, line 41 \[r1\]](https://reviewable.io:443/reviews/clusterhq/eliot/210#-K-Pa0tzNx7OYuUv8w2Q)** ([raw file](https://github.com/clusterhq/eliot/blob/a2baabc46b3063ba9c3c3dc6564e1f9d2e331ce9/eliot/tests/test_journald.py#L41)):</sup>
`-n1`?


---

<sup>**[setup.py, line 49 \[r1\]](https://reviewable.io:443/reviews/clusterhq/eliot/210#-K-PXtCHDRwvoHaG1qj3)** ([raw file](https://github.com/clusterhq/eliot/blob/a2baabc46b3063ba9c3c3dc6564e1f9d2e331ce9/setup.py#L49)):</sup>
This should be documented somewhere. I started reading the journald section, tried to run the examples and got an import error trying to import cffi.


---

<sup>**[tox.ini, line 27 \[r1\]](https://reviewable.io:443/reviews/clusterhq/eliot/210#-K-PYFF9Eq9kT1OSxN1A)** ([raw file](https://github.com/clusterhq/eliot/blob/a2baabc46b3063ba9c3c3dc6564e1f9d2e331ce9/tox.ini#L27)):</sup>
How come only py27 and py34 test journald support?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/eliot/210)

**Comment by tomprince** [comment]
<sup>**[docs/source/journald.rst, line 22 \[r2\]](https://reviewable.io:443/reviews/clusterhq/eliot/210#-K-UAP12H-yzvKXCYiBZ)** ([raw file](https://github.com/clusterhq/eliot/blob/8086e5c03c9a330c931f5bca0c5711ef2aa09781/docs/source/journald.rst#L22)):</sup>
I think it would be better if this documented using the extra. That way, if the requirements change down the line, the instructions don't need to change.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/eliot/210)

**Comment by exarkun** [comment]
No description of what this change is supposed to do - either here or on the issue.  A little help, please?

**Comment by tomprince** [comment]
This looks good. Just on concern about duplicate calculation of SYSLOG_IDENTIFIER. Merge once addressed to your satisfaction.


---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[eliot/journald.py, line 77 \[r3\]](https://reviewable.io:443/reviews/clusterhq/eliot/210#-K-UcK2_42-MX2otkaVO)** ([raw file](https://github.com/clusterhq/eliot/blob/089c16e28636f7085f71d885b4c54cf8d5a3d315/eliot/journald.py#L77)):</sup>
Do we want to be doing this calculation on every log message?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/eliot/210)

**Pull request merged**
