### PR TITLE
Define constants for field names and statuses

### PR DESCRIPTION
**Pull request by jml**
Rather than using anything nice like Python 3.4's `enum` or `twisted.python.constants`, I've just defined a bunch of variables with similar-looking names. I think this makes the code more readable and makes some of the structure of eliot more explicit.

I haven't updated usage in tests, but can if you'd like.

[Review on Reviewable](https://reviewable.io/reviews/clusterhq/eliot/200)

### CODE REVIEW

**Comment by itamarst** [comment]
Perhaps these should also be part of the public API?

**Comment by jml** [comment]
Happy to do that, perhaps as a separate patch?

**Comment by jml** [comment]
Actually, now I definitely think it should be part of a separate patch. Now that [constantly](https://github.com/twisted/constantly/) is released I'd like to look at using it. I did a quick experiment with switching the various `STATUS` fields to be `ValueConstant` and noticed two things:

 1. SUCCEEDED_STATUS et. al. get renamed to STATUS.SUCCEEDED etc. (which would break a public API)
 2. Serialization starts to fail with `exceptions.TypeError: <STATUS=STARTED> is not JSON serializable`

**Comment by itamarst** [comment]
You'd need to use ``STATUS.SUCCEEDED.value`` to prevent the serialization problems.

**Comment by itamarst** [comment]
Thanks, definitely an improvement.

**Comment by jml** [comment]
Yeah, but it's not just a simple matter of adding `.value` somewhere. It's
also finding the right places to hook into the two JSON serialization
mechanisms and converting the constants into the right form wherever we may
find them.

**Pull request merged**
